version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build: # name of your job
    machine: # executor type
      image: ubuntu-2204:2023.04.2 # # recommended linux image - includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4
    steps:
      - run: |
         sudo apt update
         sudo apt install tmate
         sudo tmate
