version: 2.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    docker:
      - image: ghcr.io/sushrut1101/docker:arch
    steps:
      - checkout
      - run:
          name: "Sync"
          command: |
            cd ~
            mkdir ~/.bin
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
            chmod a+x ~/.bin/repo
            echo "export PATH=~/bin:$PATH" >> ~/.bashrc
            # Clone the Sync Repo
            # Initialize local repository
            cd ~
            repo init --depth=1 --no-repo-verify -u https://github.com/bananadroid/android_manifest.git -b 13 --git-lfs -g default,-mips,-darwin,-notdefault
            git clone https://github.com/mitsu00/local_manifest.git --depth 1 -b banana .repo/local_manifests
            repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)

      - run:
          name: "build"
          command: |
            cd ~
            . build/envsetup.sh
            lunch banana_merlinx-user
            export ALLOW_MISSING_DEPENDENCIES=true
            export BUILD_USERNAME=ozip
            export BUILD_HOSTNAME=ozip
            export TZ=Asia/Jakarta
            mka banana