# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: ghcr.io/sushrut1101/docker:arch
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Sync"
          command: |
            cd ~
            mkdir ~/.bin
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
            chmod a+x ~/.bin/repo
            echo "export PATH=~/bin:$PATH" >> ~/.bashrc
            # Clone the Sync Repo
            # Initialize local repository
            cd ~
            repo init --depth=1 --no-repo-verify -u https://github.com/alphadroid-project/manifest -b alpha-13 --git-lfs -g default,-mips,-darwin,-notdefault
            git clone https://github.com/mitsu00/local_manifest.git --depth 1 -b alpha .repo/local_manifests
            repo sync -c --no-clone-bundle --optimized-fetch --prune --force-sync --fail-fast -j$(nproc --all)
      - run:
          name: "build"
          command: |
            echo " Test Build "
            df -h
            ls
            echo " - "
            pwd
            cd ~
            ls
            pwd
            . build/envsetup.sh
            export WITH_GAPPS=0
            ALPHA_MAINTAINER := ozipoetra
            ALPHA_BUILD_TYPE := Community
            export ALLOW_MISSING_DEPENDENCIES=true
            export BUILD_USERNAME=ozipoetra
            export BUILD_HOSTNAME=ozip.my.id
            export TZ=Asia/Jakarta
            lunch lineage_merlinx-user
            mka sepolicy
            mka bootimage
            mka init

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-workflow:
    jobs:
      - build
